here are the files that i have changed 1. added 12 couchdb for each of the peers 2. updated the ./start and ./finish script to set up and delete the dbs correctly 3. added .env file to include the {COMPOSE_PROJECT_NAME}
Problem
No longer have the 500 level error, but received
```bash
Error: error endorsing chaincode: rpc error: code = Unknown desc = access denied: channel [hachannel] creator org [House01MSP]
```